### PR TITLE
feat: renku v2 dashboard improvements

### PR DESCRIPTION
**Pull request by olevski**
/deploy

### CODE REVIEW

**Comment by olevski** [comment]
NOTE: Please rebase when updating and merging this PR.

**Comment by olevski** [comment]
This needs a new ui version. Until that is added in this PR - this is a draft.

**Comment by leafty** [comment]
> NOTE: Please rebase when updating and merging this PR.

Out of curiosity: why? Squashing with GitHub links the commit to the pull request, which is much more informative than individual commit pages.

**Comment by leafty** [comment]
> > Out of curiosity: why? Squashing with GitHub links the commit to the pull request, which is much more informative than individual commit pages.
> 
> It is nicer to have each of the two individual commits for updating the data services and ui in the history.

Well, I will disagree because the commit pages are usually useless to me. PR pages are the actual useful stuff in GitHub (discussions, reviews, etc.). Feel free to ignore this comment anyway.

**Comment by olevski** [comment]
Ok I did not know people feel so strongly about this. It is just a matter of taste but I will squash and merge.

**Review by leafty — APPROVED** [review]
Looks good. BTW, the acceptance tests should have been part of this PR (to not break the release branch).

**Pull request merged**
