### PR TITLE
chore: release 0.7.6

### PR DESCRIPTION
**Pull request by pameladelgado**
/deploy

### CODE REVIEW

**Comment by olevski** [comment]
@pameladelgado that is the correct renku-notebooks version

**Review by olevski — APPROVED** [review]

**Review by jachro — APPROVED** [review]
👍

**Review by ableuler — APPROVED** [review]
We should also bump the chart version in `helm-chart/renku/Chart.yaml`. But we can do that after master has been tagged to not restart the entire test pipeline.

**Comment by pameladelgado** [comment]
> We should also bump the chart version in `helm-chart/renku/Chart.yaml`. But we can do that after master has been tagged to not restart the entire test pipeline.

ah right, good point :+1:

**Pull request merged**
