### PR TITLE
fix: disable minio explicitly

### PR DESCRIPTION
**Pull request by pameladelgado**
/deploy

### CODE REVIEW

**Comment by ableuler** [comment]
What are you trying to achieve with this PR?

**Comment by ableuler** [comment]
As far as I can tell this won't do anything for two reasons:
1. We still use gitlab `0.5.2` in the renku requirements
2. I don't see`.Values.minio.enabled` being accessed anywhere in the templates of the gitlab chart, so I don't see how it would change the behaviour of this chart.

**Comment by pameladelgado** [comment]
@ableuler sorry, the PR wasn't ready, that's why I didnt include much description.
The minio charts were published as part of the renku charts, even if you deleted it from the gitlab requirements previously. This PR is disabling it explicitly so that those charts are not included in the renku charts and deployments can succeed in k8s versions >1.16.
This PR is ready for review now: I have pushed a new gitlab chart `0.5.3` as specified in this PR and I have published the renku chart `0.7.9-rc1` which achieves the desired effect.

**Comment by ableuler** [comment]
But minio used to be a dependency of the renku chart, not one of the gitlab chart.

**Comment by pameladelgado** [comment]
I'm closing this, the issue seen on upgrading staging is not due to a problem with the new charts but rather with what is deployed currently there. I will fix this separately.
Regarding minio being included in renku charts, I did some digging and it might have been a problem of packaging/mistagging the charts, some versions like `0.7.4` have it while other dont. After `0.7.5` when the charts were getting published with the GH action this does not seem to be a problem anymore.

**Pull request closed without merging**
