### PR TITLE
chore: Update selenium-java from 4.18.1 to 4.19.1

### PR DESCRIPTION
**Pull request by RenkuBot**
## About this PR
📦 Updates [org.seleniumhq.selenium:selenium-java](https://github.com/SeleniumHQ/selenium/) from `4.18.1` to `4.19.1`

## Usage
✅ **Please merge!**

I'll automatically update this PR to resolve conflicts as long as you don't change it yourself.

If you'd like to skip this version, you can just close this PR. If you have any feedback, just mention me in the comments below.

Configure Scala Steward for your repository with a [`.scala-steward.conf`](https://github.com/scala-steward-org/scala-steward/blob/7ec418cd5441d449f037bca6d34326534c07a5dd/docs/repo-specific-configuration.md) file.

_Have a fantastic day writing Scala!_

<details>
<summary>⚙ Adjust future updates</summary>

Add this to your `.scala-steward.conf` file to ignore future updates of this dependency:
```
updates.ignore = [ { groupId = "org.seleniumhq.selenium", artifactId = "selenium-java" } ]
```
Or, add this to slow down future updates of this dependency:
```
dependencyOverrides = [{
  pullRequests = { frequency = "30 days" },
  dependency = { groupId = "org.seleniumhq.selenium", artifactId = "selenium-java" }
}]
```
</details>

<sup>
labels: test-library-update, early-semver-minor, semver-spec-minor, commit-count:1
</sup>

/deploy

### CODE REVIEW

**Comment by rokroskar** [comment]
@jachro can we close this for now? I suppose the incompatibility will be fixed eventually, but it's not critical for us to have this update, correct?

**Comment by eikek** [comment]
No, not at all critical to me. We can close it or leave it open as a reminder.

**Comment by rokroskar** [comment]
ok lets close it then unless we want to invest time in fixing the chromium/selenium incompatibility?

**Comment by jachro** [comment]
I was thinking to look into that later today or tomorrow.

**Comment by jachro** [comment]
I might be wrong but it looks to me that the problem comes from incompatibility between selenium driver and chromium. I tried some suggestions from other people but it didn't work. Yes, let's maybe wait until some new version of `chromium-driver` is available for `python:3.9-slim` that we use in the container.

**Pull request closed without merging**
