### PR TITLE
chore: Upgrade Redis to v7.2.5.

### PR DESCRIPTION
**Pull request by aledegano**
/deploy

### CODE REVIEW

**Review by Panaetius — APPROVED** [review]

**Comment by aledegano** [comment]
I have just realized that it would be more prudent to make a migration test before merging this.
So for now I will leave it on hold.

**Comment by aledegano** [comment]
> I have just realized that it would be more prudent to make a migration test before merging this. So for now I will leave it on hold.

Correction: for the time being we are (still) not persisting Redis data, so for now we can upgrade without a problem.

**Comment by rokroskar** [comment]
@aledegano want to revive this?

**Comment by aledegano** [comment]
> @aledegano want to revive this?

Yes, I will get to it ASAP.

**Comment by aledegano** [comment]
Superseded by #3855

**Pull request closed without merging**
