### PR TITLE
Configure the Renku realm to use the Renku keycloak theme

### LINKED ISSUE #2022: Enable custom theme on keycloak
Following the keycloak upgrade #1900 the custom theme for keycloak screen is not working properly, we need to enable/fix this.

### PR DESCRIPTION
**Pull request by ciyer**
Fix #2022

/deploy

### CODE REVIEW

**Comment by ciyer** [comment]
Switching to the new renku-theme **fixes** the "internal server error" problem that was occurring before. The change to `init-realm.py` **does not** automatically activate the renku theme (even though that works locally). ATM, an admin needs to switch the theme to get the renku theme.

**Comment by rokroskar** [comment]
@ciyer what's the status here? (it's still a draft) 

Where was the "internal server error" occurring?

**Comment by ciyer** [comment]
> Where was the "internal server error" occurring?

The old Keycloak theme would cause an "internal server error" when you tried to get to the log in screen.

**Comment by rokroskar** [comment]
can we adjust the acceptance test here as well? 

20210622090751-LoginSpec

**Comment by ciyer** [comment]
> can we adjust the acceptance test here as well?

The Renku login page is not activated by default. A Keycloak admin needs to actively turn it on, so the tests do not need to be modified.

**Comment by rokroskar** [comment]
hmm... then the test needs to work with both cases - we need to be able to run the acceptance tests in production as well

**Comment by rokroskar** [comment]
so you enabled it by hand for the deployment in this PR?

**Comment by ciyer** [comment]
> so you enabled it by hand for the deployment in this PR?

Yes.

**Comment by ableuler** [comment]
> > so you enabled it by hand for the deployment in this PR?
> 
> Yes.

Are you sure that's true? It seems to me that the CI deployment is older than the commit which adds this:

image

The realm is only created at first deploy, but on a fresh redeploy I'd expect the realm to be created with the right template.

**Comment by ciyer** [comment]
> hmm... then the test needs to work with both cases - we need to be able to run the acceptance tests in production as well

I have added a commit that fix the acceptance tests to work with both login screens, the keycloak default and the Renku screen.

**Comment by ableuler** [comment]
I deleted everything in those namespaces (except the TLS secret) and redeployed, now the renku-theme was activated from the start.

**Comment by ableuler** [comment]
> can we adjust the acceptance test here as well?
> 
> 20210622090751-LoginSpec

Did you test this on a keycloak instance which has upstream identity providers configured?

**Review by rokroskar — APPROVED** [review]
Thanks @ciyer!!

**Comment by ciyer** [comment]
> Did you test this on a keycloak instance which has upstream identity providers configured?

Yes, that also works.

**Pull request merged**
