### PR TITLE
chore: use new ingress anotation for cert-manager

### PR DESCRIPTION
**Pull request by aledegano**

### CODE REVIEW

**Review by pameladelgado — COMMENTED** [review]
From what I understand the deprecated `ingress.class` annotation is still needed for k8s <1.18 and nginx-ingress, so I would keep it there for the moment.

**Comment by aledegano** [comment]
> From what I understand the deprecated `ingress.class` annotation is still needed for k8s <1.18 and nginx-ingress, so I would keep it there for the moment.

uhm... that is strange because I have tested in my namespace in `dev`:

1. removing `ingress.class`
2. adding the new annotation
3. deleting the existing certificate

And it recreated the certificate correctly.

**Comment by pameladelgado** [comment]
> > From what I understand the deprecated `ingress.class` annotation is still needed for k8s <1.18 and nginx-ingress, so I would keep it there for the moment.
> 
> uhm... that is strange because I have tested in my namespace in `dev`:
> 
>     1. removing `ingress.class`
> 
>     2. adding the new annotation
> 
>     3. deleting the existing certificate
> 
> 
> And it recreated the certificate correctly.

Right, but this annotation is for the ingress, not for the certificate. So to test this you would need to recreate the ingresses.

**Comment by aledegano** [comment]
> > > From what I understand the deprecated `ingress.class` annotation is still needed for k8s <1.18 and nginx-ingress, so I would keep it there for the moment.
> > 
> > 
> > uhm... that is strange because I have tested in my namespace in `dev`:
> > ```
> > 1. removing `ingress.class`
> > 
> > 2. adding the new annotation
> > 
> > 3. deleting the existing certificate
> > ```
> > 
> > 
> > And it recreated the certificate correctly.
> 
> Right, but this annotation in particular is for the ingress, not for the certificate. So to test this you would need to recreate the ingresses.

Oh, right! I was confused!
I'll fix this and all other PRs! Sorry for the noise!

**Review by pameladelgado — APPROVED** [review]
Looks good! :+1:

**Pull request merged**
