### PR TITLE
build: add uiserver.sentry to values

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
/deploy #notest

### CODE REVIEW

**Review by andre-code — APPROVED** [review]
Ready to merge 🚀

**Review by rokroskar — APPROVED** [review]

**Comment by rokroskar** [comment]
I'm not sure why you need to deploy and test this, it's not actually modifying anything?

**Comment by lorenzo-cavazzi** [comment]
> I'm not sure why you need to deploy and test this, it's not actually modifying anything?

Ehm... true :sweat_smile:

**Comment by lorenzo-cavazzi** [comment]
Still, it failed :grimacing:

**Comment by rokroskar** [comment]
yes but anything KG-related on dev is a bit touchy atm because of the reprovisioning

**Comment by rokroskar** [comment]
I'm not sure it's related to this change...

**Comment by lorenzo-cavazzi** [comment]
> I'm not sure it's related to this change...

For sure not.

Anyway, I still need a @SwissDataScienceCenter/kartografen approval to merge this

**Pull request merged**
