### PR TITLE
chore: update renku-python to 2.7.0

### PR DESCRIPTION
**Pull request by olevski**
/deploy #persist extra-values=notebooks.userSessionPersistentVolumes.enabled=true

### CODE REVIEW

**Review by bethcg — APPROVED** [review]

**Comment by olevski** [comment]
We know that the `testDatasets` test that fails is flaky. So I will ignore it. Lorenzo submitted a fix for the test flakiness in a another PR.

**Comment by lorenzo-cavazzi** [comment]
I didn't realize the other PR wasn't close to being merged. Should I reopen this? #3278

**Comment by olevski** [comment]
> I didn't realize the other PR wasn't close to being merged. Should I reopen this? https://github.com/SwissDataScienceCenter/renku/pull/3278

Just leave it. I dont want to restart the tests fully here.

**Review by aledegano — APPROVED** [review]

**Comment by olevski** [comment]
I have confirmed all failing tests are either flaky or are known issues not introduced by the chnages here. So I am merging this.

**Pull request merged**
