### PR TITLE
feat(chart): combine all Renku component Helm charts

### PR DESCRIPTION
**Pull request by olevski**
/deploy #persist extra-values=initDb.image.repository=registry.dev.renku.ch/tasko.olevski/renku-images/init-db,initDb.image.tag=0.36.4-8.21cbfb5,keycloakx.initRealm.image.repository=registry.dev.renku.ch/tasko.olevski/renku-images/init-realm,keycloakx.initRealm.image.tag=0.36.4-8.21cbfb5

### CODE REVIEW

**Comment by rokroskar** [comment]
This is really great @olevski ! I think there might be some inconsistencies in how the labels (and probably other parameters) are applied/computed - e.g. in the case of the `ui` there is simply `ui` but with notebooks and gateway it's e.g. `{{ template "renku.name" . }}-gateway-auth` and for KG services it is `{{ template "renku.graph.commitEventService.name" . }}` - I'm not sure if you want to make this consistent in this PR or not, but it should at least be handled with some urgency in a follow-up, otherwise it's going to continue to be hard to maintain and debug.

**Comment by olevski** [comment]
@rokroskar I want to do these things right after things are merged. Because the long this PR stays open the more complicated and hard it becomes to maintain it.

**Review by bethcg — DISMISSED** [review]

**Comment by olevski** [comment]
For anyone who is reviewing this, this is a diff between the components moved to the this repo from each copmonent repo. This diff compares across the component repositories and renku. Because all templates from the component repositories were moved to this repository. And the diff of this PR only shows additions. 

Just download the html file and view it in your browser.

https://drive.google.com/file/d/1fZeC_9R9Kc6M-y2s5O3ZBFlqkrlzoHBP/view?usp=sharing

**Review by bethcg — APPROVED** [review]

**Review by aledegano — APPROVED** [review]
@olevski showed me this PR last Friday during the Renku meeting.
I am okay with the changes.

**Pull request merged**
