### PR TITLE
demo user not gitlab admin

### LINKED ISSUE #242: Remove or make optional demo user as gitlab admin
User `demo` should not be a gitlab admin:
https://github.com/SwissDataScienceCenter/renku/blob/4d4d1c888e8b64b3635a35b21a447ba8fb0211ba/charts/renku/templates/configmap.yaml#L42-L43

### PR DESCRIPTION
**Pull request by leafty**
Fix #242

### CODE REVIEW

**Comment by rokroskar** [comment]
Making the demo user an admin was not an accident -- but until we have another admin user (e.g. gitlab-admin?) this is the only way to not get locked out of gitlab if we also want to not go through the gitlab login page. So yes, I agree `demo` should not be an admin user, but this needs to be done by first completing https://github.com/SwissDataScienceCenter/renku/pull/212. I suggest we close this PR and make the change in #212 instead.

**Comment by leafty** [comment]
Why would you be locked out? I believe you can register on keycloak to create new accounts and the admin token is linked to user `root` so will continue to work.

**Comment by rokroskar** [comment]
Might work, didn't try that

**Comment by ableuler** [comment]
You can do what @leafty described, but it would be nice to have this automated rather than having to create an new user through kc and make it admin through the gitlab api every time you restart the platform.

**Comment by leafty** [comment]
@ableuler Made it optional with sensible default.
Please merge quickly, as I don't like having demo being put back as admin with every CD update.

**Pull request merged**
