### PR TITLE
chore: add info about the check description action

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
@rokroskar here is a follow-up of you suggestion here: https://github.com/SwissDataScienceCenter/renku/pull/2064#issuecomment-818531373

It's a short description of the `check pr description` action. I'll add more details on how to use the `/deploy` command in our infrastructure in the internal docs repo https://github.com/SwissDataScienceCenter/sdsc-dev-docs

### CODE REVIEW

**Comment by lorenzo-cavazzi** [comment]
Added the information initially pushed here SwissDataScienceCenter/sdsc-dev-docs#87

**Comment by ableuler** [comment]
This is really useful! Is the target audience for the contributing guide people who don't have write access to our repos? Then I'd just mention the workflow which uses a fork and where we merge the PR.

**Comment by lorenzo-cavazzi** [comment]
> This is really useful! Is the target audience for the contributing guide people who don't have write access to our repos? Then I'd just mention the workflow which uses a fork and where we merge the PR.

Yup that should target also people without write permissions in our repo, although the idea is to mention our usual flow mainly to simplify life for people who joined the team.

I mention this:
> Create a new branch, either on the target repository or on your fork,  and open a pull request to merge the branch to `master`.

Do you mean we should explain better how to fork and open a PR to merge in the official repo from the fork? I think that's standard GitHub flow, not sure if we want to detail that part too much. Or did I not get the suggestion?

**Comment by rokroskar** [comment]
> to simplify life for people who joined the team

keep in mind we want to keep the option of having contributors/maintainers outside of our org so I think this makes sense where it is now.

**Comment by lorenzo-cavazzi** [comment]
@rokroskar @ableuler Is there something I should change on this PR or can we merge it?

**Review by ableuler — APPROVED** [review]
> @rokroskar @ableuler Is there something I should change on this PR or can we merge it?

Let's merge it! 👍

**Pull request merged**
