### PR TITLE
test: update text to open existing session from open to connect (#1831)

### PR DESCRIPTION
**Pull request by andre-code**
PR to update tests for new button texts.

/deploy renku-ui=master #persist

### CODE REVIEW

**Comment by lorenzo-cavazzi** [comment]
Not sure why @SwissDataScienceCenter/renku-product-management was asked for a review since it doesn't touch files other than tests :thinking: 
Maybe we need to tweak a setting.

**Comment by lokijuhy** [comment]
@lorenzo-cavazzi Huh, ok. I'm not sure why I got tagged as a reviewer, since the Changelog wasn't touched anyway. I took myself off the PR 🤷‍♀️

**Comment by lorenzo-cavazzi** [comment]
I have limited permissions on this repo. Let me tag @rokroskar to fix the folder-based review requests

**Comment by rokroskar** [comment]
I think @andre-code may have requested those reviews?

**Comment by lorenzo-cavazzi** [comment]
This has been merged to #2919
Keeping this open for a little longer to prevent disrupting acceptance tests in the UI repo

**Comment by lorenzo-cavazzi** [comment]
Oh actually, I can already close this (since it was already merged) and restore the branch -- that's enough for the UI tests

**Pull request closed without merging**
