### PR TITLE
feat: add trusted proxies configuration to data-service

### PR DESCRIPTION
**Pull request by leafty**
See: SwissDataScienceCenter/renku-data-services#225

/deploy

### CODE REVIEW

**Comment by olevski** [comment]
And lastly please target the new release branch. `release-0.53.x`

**Comment by leafty** [comment]
> And lastly please target the new release branch. `release-0.53.x`

Can we cleanup that branch first? The changes are crazy if I do the switch.

**Comment by leafty** [comment]
> Also shouldn't the proxy count be 2? Because in most cases the ui will call this through the ui-server, which will then go through the gateway and finally reach the data service.

I think our network hops do not behave as proper reverse proxies should, so for now using `1` as the proxies count value makes the HTTP scheme detection work.

**Comment by leafty** [comment]
> @leafty this requires changes on both the ui-server and the gateway so that this secret is used and set in incoming requests, correct? Or am I misunderstanding the examples/config from the sanic docs here: https://sanic.dev/en/guide/advanced/proxy-headers.md#getting-started

Yes, I removed the forwarded secret value. We can try to address this in the future.

**Review by Panaetius — APPROVED** [review]

**Pull request merged**
