### PR TITLE
chore: notebooks 1.22.0

### PR DESCRIPTION
**Pull request by mana-alisafaee**
This PR includes the new functionality for Renku 2 sessions.

### CODE REVIEW

**Comment by rokroskar** [comment]
Looks like this needs a rebase @mana-alisafaee

**Comment by rokroskar** [comment]
Or rather, just remove the two extra commits and it should be gtg

**Comment by leafty** [comment]
Note that `notebooks` is already being updated in #[3478](https://github.com/SwissDataScienceCenter/renku/pull/3478).

**Comment by mana-alisafaee** [comment]
> Or rather, just remove the two extra commits and it should be gtg

I did it but release note for `0.49.1` is missing.

**Comment by rokroskar** [comment]
yes because the `release-0.50.x` branch has not been made up to date with `master` yet. In a moment :)

**Comment by rokroskar** [comment]
> Note that `notebooks` is already being updated in #3478.

This just adds the change to the changelog atm - but I suppose that can be done together in https://github.com/SwissDataScienceCenter/renku/pull/3556?

**Comment by mana-alisafaee** [comment]
I close this one in favor of https://github.com/SwissDataScienceCenter/renku/pull/3556.

**Pull request closed without merging**
