### PR TITLE
feat: Add URL for KG OpenAPI spec

### PR DESCRIPTION
**Pull request by travissarles**
feat: Add URL for KG OpenAPI spec

### CODE REVIEW

**Comment by travissarles** [comment]
> You can access the deployment of this PR at https://ci-renku-2654.dev.renku.ch

It is not. We're in the process of making it public. I suppose we can wait until it is.

**Comment by rokroskar** [comment]
Yes this won't work until it's exposed.

**Review by jachro — APPROVED** [review]

**Comment by rokroskar** [comment]
@jachro @travissarles I'd like to deploy this to test before we merge if that's ok

**Comment by jachro** [comment]
> @jachro @travissarles I'd like to deploy this to test before we merge if that's ok

Sure.

**Comment by rokroskar** [comment]
You have `renkulab.io` hard-coded in the api spec - that should not be the case: 

image

We can merge this since the change has to happen elsewhere, but the swagger page is not currently usable.

**Review by rokroskar — APPROVED** [review]

**Comment by jachro** [comment]
Yes, we noticed that. Travis is preparing a quick fix for this.

**Comment by rokroskar** [comment]
Another thing I noticed was that even though I provided a token, it was not added to the request.

**Comment by rokroskar** [comment]
This doesn't need acceptance tests to pass, does it?

**Comment by jachro** [comment]
That's true. Let me take the `/deploy`, then.

**Pull request merged**
