### PR TITLE
docs: Update "Get started" tutorial to match the UI style (#3181)

### PR DESCRIPTION
**Pull request by andre-code**
Closes https://github.com/SwissDataScienceCenter/renku/issues/3181

### CODE REVIEW

**Review by rokroskar — CHANGES_REQUESTED** [review]
Thanks a lot @andre-code !!

Two minor things: 

1. There is one page where the formatting is a bit weird - it shows the gitlab and renkulab views on top of each other and it's hard to tell which is which:

image

Adding some text in between the two figures would solve that. 

2. I also find it a little confusing to have the red box around the main action button, when the image shows the drop-down - intuitively if I were following the instructions I would probably click the main button expecting the drop-down, but that's not what happens.

**Comment by andre-code** [comment]
Thanks @rokroskar I have applied the suggestions and also rewrite it a bit the part of creating Issues in Gitlab.

**Comment by rokroskar** [comment]
Thanks @andre-code! I think the same issue with the drop-down can be seen in this image:

image

I'm not sure though if from the text context it's enough to understand... maybe the red box number "2" can also extend to the drop-down? not sure what the best way is

**Comment by andre-code** [comment]
> Thanks @andre-code! I think the same issue with the drop-down can be seen in this image:
> 
> image
> 
> I'm not sure though if from the text context it's enough to understand... maybe the red box number "2" can also extend to the drop-down? not sure what the best way is

sure!
I have changed the image to make the steps clearer for these cases.

**Review by rokroskar — APPROVED** [review]
Thanks!!

**Pull request merged**
