### PR TITLE
docs: add documentation for template icons

### PR DESCRIPTION
**Pull request by Panaetius**
depends on https://github.com/SwissDataScienceCenter/renku-python/pull/2339

### CODE REVIEW

**Review by rokroskar — APPROVED** [review]
🚀

**Comment by rokroskar** [comment]
@Panaetius any reason not to merge this?

**Comment by Panaetius** [comment]
Well I guess I disabled notifications for most repos and forgot about it :sweat_smile:

**Comment by lorenzo-cavazzi** [comment]
Isn't this part of the yet unreleased v1.0?

**Comment by rokroskar** [comment]
@lorenzo-cavazzi presumably it will be in the next renku release...

**Pull request merged**
