### PR TITLE
feat: run Helm test for Renku CD

### LINKED ISSUE #1944: Run acceptance test on CD deployment through helm test
Currently, the acceptance tests in the `deploy` workflow are still run through docker-compose. We should modify this according to what has been done for the PR test deployments.

### PR DESCRIPTION
**Pull request by aledegano**
When running the deploy action for Renku, use helm test to pilot the acceptance test instead of docker-compose.

Depends on swissdatasciencecenter/ops-dev.renku.ch#121

closes #1944

### CODE REVIEW

**Comment by aledegano** [comment]
I don't think this change can be tested (?).
In any case before merging the change in SwissDataScienceCenter/ops-dev.renku.ch#121 must be included in the secret `CD_VALUES` of the GH actions.

**Comment by rokroskar** [comment]
@aledegano yes it can - change [this line](https://github.com/SwissDataScienceCenter/renku/blob/217badd9e1376792a86dea8ceed346f28bad526f/.github/workflows/deploy.yml#L5) to point to this branch

**Comment by aledegano** [comment]
> @aledegano yes it can - change [this line](https://github.com/SwissDataScienceCenter/renku/blob/217badd9e1376792a86dea8ceed346f28bad526f/.github/workflows/deploy.yml#L5) to point to this branch

Ah, great, I'll check it out, thanks!

**Comment by aledegano** [comment]
Tested, works! https://github.com/SwissDataScienceCenter/renku/pull/1952/checks?check_run_id=1870403719

**Comment by rokroskar** [comment]
did you update the secret? If yes, then you should revert the last commit ;)

**Comment by aledegano** [comment]
> did you update the secret? If yes, then you should revert the last commit ;)

Yes, I had to update the secret to have all the required values. Sure, I'll revert the commit now :)

**Review by rokroskar — APPROVED** [review]

**Comment by rokroskar** [comment]
Btw, this is the correct run where the PR was tested: https://github.com/SwissDataScienceCenter/renku/actions/runs/554230086

**Review by rokroskar — COMMENTED** [review]
🚀

**Review by rokroskar — APPROVED** [review]
sorry, meant to approve 🚀 🚀

**Review by pameladelgado — APPROVED** [review]
Great, thanks!

**Pull request merged**
