### PR TITLE
[WIP] add keycloak as explicit dependency

### PR DESCRIPTION
**Pull request by fgeorgatos**
initiating a working area for this...

- [ ] script that uses REST API to set up the renku keycloak realm
- [ ] initialize keycloak in the `start-renku` script for dev environment with the `Makefile`
- [ ] initialize keycloak in the helm post-install hook

closes https://github.com/SwissDataScienceCenter/renku/issues/214 
addresses #208

### CODE REVIEW

**Comment by leafty** [comment]
Now, the hard part is finding a way to push the contents of https://github.com/SwissDataScienceCenter/renku/blob/master/charts/renku/charts/keycloak/templates/_renku-realm.tpl into keycloak somehow.

**Comment by rokroskar** [comment]
is this still being worked on? Did @ebiiii take it over?

**Comment by leafty** [comment]
Progress won't be fast, we'll need to rewrite the realm template as a script.

**Comment by leafty** [comment]
Closing in favor of #336

**Pull request closed without merging**
