### PR TITLE
Updates for Renku 0.9.1

### PR DESCRIPTION
**Pull request by pameladelgado**

### CODE REVIEW

**Review by jachro — APPROVED** [review]

**Comment by rokroskar** [comment]
This needs to be on a bugfix branch - either that or the amalthea commits reversed

**Comment by pameladelgado** [comment]
> This needs to be on a bugfix branch

this **is** a bugfix branch, based on `0.9.0`

**Comment by rokroskar** [comment]
no, it's merging into master

**Comment by rokroskar** [comment]
you need to make a PR on top of the 0.9.x branch, not the master branch

**Comment by pameladelgado** [comment]
> 
> 
> no, it's merging into master

the plan was not to merge it to master, but I see your point. I could do a PR and make it merge to the bugfix branch, or just dont have a PR altogether since the changes are already there.

**Comment by rokroskar** [comment]
I think it probably should be merged to master, no? and then you can cherry pick it to the branch without amalthea.

**Comment by pameladelgado** [comment]
> 
> 
> I think it probably should be merged to master, no? and then you can cherry pick it to the branch without amalthea.

Either that or make the chart/changelog changes in another PR, the change on the graph requirements is already included and tested in #2282.
In the meantime I've already tagged the changes in the branch and the pipeline is being tested on staging.

**Pull request closed without merging**
