### PR TITLE
docs(crc): add basic documentation on adminstering crc

### PR DESCRIPTION
**Pull request by seanrmurphy**
Add some basic content on how to manage the CRC service.

### CODE REVIEW

**Review by rokroskar — CHANGES_REQUESTED** [review]
Thanks @seanrmurphy - some minor comments. In general, it would be nice to add a small intro about the service itself but can do that separately.

**Comment by rokroskar** [comment]
@seanrmurphy can we try to merge this?

**Comment by seanrmurphy** [comment]
@rokroskar - i think i've addressed your comments - lmk if you need me to change anything else...

**Review by rokroskar — APPROVED** [review]
Thanks @seanrmurphy !

**Review by rokroskar — APPROVED** [review]
Thanks!!

**Pull request merged**
