### PR TITLE
chore: renku-graph 2.50.0 (with Jena 5.0.0)

### PR DESCRIPTION
**Pull request by jachro**
This PR:
* upgrades renku-graph to `2.50.0`
* upgrades Jena to `5.0.0`

/deploy

### CODE REVIEW

**Review by lokijuhy — CHANGES_REQUESTED** [review]
Should this PR be targeting the 0.50.0 release branch?

**Comment by jachro** [comment]
> Should this PR be targeting the 0.50.0 release branch?

Thanks Laura! Yes, it should (and it is now).

**Review by rokroskar — COMMENTED** [review]
Any changelog changes required @jachro ?

**Comment by rokroskar** [comment]
@jachro this PR doesn't actually change the graph service versions - did you forget to push a change?

**Comment by jachro** [comment]
> @jachro this PR doesn't actually change the graph service versions - did you forget to push a change?

I've done it just now as I was testing the jena chart version update on our KG env and needed a PR on renku with the `requirement.yaml` tweak.

**Comment by rokroskar** [comment]
got it! thanks!

**Comment by rokroskar** [comment]
Did you try applying this change to an existing deployment with the previous version of Jena?

**Comment by jachro** [comment]
> Did you try applying this change to an existing deployment with the previous version of Jena?

Yes, I've tested that on our [KG](https://renku-kg-dev.dev.renku.ch/) env.

**Review by rokroskar — APPROVED** [review]

**Pull request merged**
