### PR TITLE
Renku hotfix for 0.4.2

### PR DESCRIPTION
**Pull request by jachro**
This PR creates a hotfix release 0.4.3 for Renku 0.4.2. The only change is a new version of renku-graph.

### CODE REVIEW

**Comment by jachro** [comment]
I guess I was doing that. Let me check if I screwed it up...

**Comment by jachro** [comment]
And I believe this PR should never be merged as this changes should never go to master.

**Comment by rokroskar** [comment]
Then it shouldn't be a PR to the master branch but to the hotfix branch. Or no PR at all. See https://github.com/SwissDataScienceCenter/sdsc-dev-docs/tree/master/renku-release#hotfixes

**Comment by jachro** [comment]
Right. Sorry I wasn't aware of the process. Fixing my mistake...

**Comment by jachro** [comment]
I fixed my mistake. I renamed the branch to `0.4.3` but it was originated from the `0.4.2` tag so the changes should be all good.
```
* 20db63f (HEAD -> 0.4.3, origin/0.4.3) chore: hotfix 0.4.3 version of Renku
* 102a330 chore: bumped renku-graph version to include the hotfix
* 09e7387 (tag: 0.4.2) build: update dependencies for 0.4.2 (#627)
```
Should I close this PR?

**Comment by rokroskar** [comment]
Great thanks! 

> Should I close this PR?

You already did :)

**Comment by jachro** [comment]
Ops, true :)

**Pull request closed without merging**
