### PR TITLE
Add gitlab-admin to keycloak

### PR DESCRIPTION
**Pull request by ableuler**
Add a gitlab-admin user (gitlab-admin / gitlab-admin) to the keycloak realm, make this user a gitlab admin instead of the demo user.

### CODE REVIEW

**Comment by rokroskar** [comment]
This also seems to break gitlab logout -- not sure what changed with the client setup?

**Comment by ableuler** [comment]
I plan to revisit this when tackling https://github.com/SwissDataScienceCenter/renga/issues/214, let's leave the PR open until then.

**Comment by rokroskar** [comment]
I think with #264 closed we can close this PR?

**Comment by ableuler** [comment]
@rokroskar agree

**Pull request closed without merging**
