### PR TITLE
build(ci): deploy tags

### PR DESCRIPTION
**Pull request by rokroskar**
One more fix for new travis behavior...

### CODE REVIEW

**Comment by rokroskar** [comment]
We do - except for here apparently. :)

**Comment by rokroskar** [comment]
btw a tagged build is running right now... if it completes without issue I'll merge

**Comment by ableuler** [comment]
> We do - except for here apparently. :)

Ah true - has been there for only 6 months 🙈

**Comment by rokroskar** [comment]
@ableuler yes I put this in everywhere except for this repo because of the annoying circular dependency on our gitlab chart. We should factor out the gitlab chart as well and then everything will be fine.

**Pull request merged**
