### PR TITLE
Updates post 0.5.2 release

### PR DESCRIPTION
**Pull request by pameladelgado**
Travis allows tags labels that use `-rc` followed by one or more digits.
Updated changelog.

### CODE REVIEW

**Comment by pameladelgado** [comment]
> Do we need to bump the chart version?

yes that too, but I think it should not be 0.5.2 since there are new versions of other components on master, which value do you propose we use? we should probably have a policy for setting up the chart versions...

**Comment by rokroskar** [comment]
I would call it 0.6.0 for now because unless there are bug fixes the next version will probably include the new renku-core service.

**Comment by pameladelgado** [comment]
That's the actual value now, I guess we will leave it as is in master.

**Comment by rokroskar** [comment]
Ah indeed. Oops, sorry!

**Pull request merged**
