### PR TITLE
Fix dead link to helm installation documentation.

### PR DESCRIPTION
**Pull request by dunatotatos**

### CODE REVIEW

**Comment by dunatotatos** [comment]
Not sure why it fails. I doubt we can blame the commit ^^

**Comment by rokroskar** [comment]
Hi @dunatotatos definitely not your fault - it's because our CI requires repo write permissions. I will open another PR with your commit to make this go through. Thanks for the correction!

**Comment by rokroskar** [comment]
actually, turns out that pushing the same commit to a different branch does the trick :) So I'll go ahead and approve/merge this PR instead of the other one.

**Review by rokroskar — APPROVED** [review]
Thanks @dunatotatos for fixing this!

**Pull request merged**
