### PR TITLE
feat: use rollout renku deployment action

### PR DESCRIPTION
**Pull request by pameladelgado**
Use rollout renku action (https://github.com/SwissDataScienceCenter/renku-actions/pull/31) on tagging, to automate the rollout process of quick releases.

### CODE REVIEW

**Comment by pameladelgado** [comment]
Ready for review, see result in https://github.com/SwissDataScienceCenter/terraform-renku/compare/auto-update/renku-0.12.17?expand=1

Need to update the reference after a tag is made in renku-actions.

**Comment by rokroskar** [comment]
The failing `check-deploy` is a feature, not a bug - your PR should not be without a description ;)

**Comment by rokroskar** [comment]
Looks like the [changelog link](https://github.com/SwissDataScienceCenter/terraform-renku/compare/auto-update/renku-0.12.17?expand=1#diff-86e35518f6d48a8591487623a2f028caa0d6c7fb3d489c9923d70b6f176d13beR190) is not quite right?

**Comment by pameladelgado** [comment]
> Looks like the [changelog link](https://github.com/SwissDataScienceCenter/terraform-renku/compare/auto-update/renku-0.12.17?expand=1#diff-86e35518f6d48a8591487623a2f028caa0d6c7fb3d489c9923d70b6f176d13beR190) is not quite right?

Thanks, I've noticed that too, will submit a fix soon!

**Comment by pameladelgado** [comment]
> Looks like the [changelog link](https://github.com/SwissDataScienceCenter/terraform-renku/compare/auto-update/renku-0.12.17?expand=1#diff-86e35518f6d48a8591487623a2f028caa0d6c7fb3d489c9923d70b6f176d13beR190) is not quite right?

this is fixed now

**Review by aledegano — APPROVED** [review]

**Comment by aledegano** [comment]
Thank you for this automation!

**Pull request merged**
