### PR TITLE
Rework Renku v2 design - part 1

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
New design for Renku 2.0
This is the first of two iterations meant to be shipped in a short sequence.

Please refer to the UI PR for more information https://github.com/SwissDataScienceCenter/renku-ui/pull/3214

/deploy

### CODE REVIEW

**Review by leafty — COMMENTED** [review]
~~Note: user secrets will not work until https://github.com/SwissDataScienceCenter/renku/pull/3716 is merged.~~

**Comment by lorenzo-cavazzi** [comment]
> Note: user secrets will not work until #3716 is merged.

Do you mean incidents and maintenance sections?
I don't see user secrets mentioned in that PR

**Comment by leafty** [comment]
Actually no. They break when `renku-data-services 0.17.0 -> 0.18.0`.

**Comment by lorenzo-cavazzi** [comment]
> Actually no. They break when `renku-data-services 0.17.0 -> 0.18.0`.

Ok. I don't think that relates to the changes in this PR and it might better be addressed somewhere else.

**Comment by leafty** [comment]
> > Actually no. They break when `renku-data-services 0.17.0 -> 0.18.0`.
> 
> Ok. I don't think that relates to the changes in this PR and it might better be addressed somewhere else. Unless I'm missing context

The comment had been retracted.

**Comment by lorenzo-cavazzi** [comment]
For some reason, I can't reopen this PR :shrug: 

See #3726

image

**Pull request closed without merging**
