### PR TITLE
singleuser: install renku and git-lfs

### LINKED ISSUE #239: reduce the size of images
the `renku` notebook images are based on the `jupyter` docker stacks and seem quite large. E.g. 

```
docker images --filter "reference=renku/singleuser*"
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
renku/singleuser    285198f23f0c        776527be099c        9 hours ago         2.8GB
```

This is based on the `jupyter/minimal-notebook` image, which itself is about the same size. Could we use a different base image to reduce the image size?

### PR DESCRIPTION
**Pull request by jirikuncar**
~~Simplifies the build process for `singleuser` image.~~
~~Adds Git and Git-LFS since the image no longer depends on `renku/minimal-notebook`~~
- Installs `renku-python` from master or defined tag.

closes #325 (includes)
closes #239

### CODE REVIEW

**Comment by leafty** [comment]
(cc @rokroskar) Isn't this a duplicate of #325 ?

**Comment by rokroskar** [comment]
@leafty #325 doesn't install `renku-python`

**Comment by leafty** [comment]
Then either rebase this one or make a new one to add `renku-python` in it.

**Comment by mitch-volpi** [comment]
I need Git-LFS.

**Comment by 3C111** [comment]
Git-lfs is included in the single-user Docker image.

**Comment by rokroskar** [comment]
@mitch-volpi in your `Dockerfile` for your project can you specify to use `renku/singleuser:dec8e6a` instead of `renku/singleuser:latest`?

`git-lfs` is installed but looks like a new image needs to be pulled to `internal.renku.ch`. This is a separate issue. 

This PR can stay open but tests need to pass and scope is installation of the `renku` CLI.

**Comment by mitch-volpi** [comment]
@rokroskar I changed the Dockerfile to use renku/singleuser:dec8e6a and the image has been rebuilt succesfully.  I also have git-lfs thanks to @jirikuncar.

**Comment by rokroskar** [comment]
@mitch-volpi I'm confused, so git-lfs wasn't there?

**Comment by mitch-volpi** [comment]
@rokroskar apparently not, @jirikuncar knows the details. We basically install it from scripts in the Dockerfile, as in LL15-19 of https://github.com/SwissDataScienceCenter/renku/pull/329/files#diff-e806328181a016b7c23b332086ef38fd

**Comment by rokroskar** [comment]
as far as I can tell, git-lfs is working fine in the `renku/singleuser` image -- can we close this?

**Comment by rokroskar** [comment]
I am closing this PR as it seems to have gone into hibernation. I'm happy if someone revives it, but it seems to me that the problems its solving have been solved elsewhere.

**Pull request closed without merging**
