### PR TITLE
jh: fix singleuser image tag

### LINKED ISSUE #230: notebook spawn fails
Notebooks fail to spawn due to a wrong entrypoint.

### PR DESCRIPTION
**Pull request by rokroskar**
closes #230

### CODE REVIEW

**Comment by erbou** [comment]
Renku starts and the demo script works, but when I launch a notebook I get a '404' from http://jupyterhub.renku.build.

**Comment by rokroskar** [comment]
@erbou can you paste the results of

```
$ docker-compose logs jupyterhub
```

**Comment by erbou** [comment]
Attaching to renku_jupyterhub_1
[36mjupyterhub_1     |[0m [D 2018-05-22 11:42:54.323 JupyterHub application:555] Looking for jupyterhub_config in /srv/jupyterhub
[36mjupyterhub_1     |[0m [D 2018-05-22 11:42:54.413 JupyterHub application:577] Loaded config file: /srv/jupyterhub/jupyterhub_config.py
[36mjupyterhub_1     |[0m [D 2018-05-22 11:42:55.951 JupyterHub app:866] Generating new cookie_secret
[36mjupyterhub_1     |[0m [I 2018-05-22 11:42:55.957 JupyterHub app:871] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[36mjupyterhub_1     |[0m [D 2018-05-22 11:42:55.958 JupyterHub app:886] Connecting to db: sqlite:///jupyterhub.sqlite
[36mjupyterhub_1     |[0m [D 2018-05-22 11:42:56.003 JupyterHub orm:475] Stamping empty database with alembic revision 3ec6993fe20c
[36mjupyterhub_1     |[0m [I 2018-05-22 11:42:56.020 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
[36mjupyterhub_1     |[0m [I 2018-05-22 11:42:56.023 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
[36mjupyterhub_1     |[0m [I 2018-05-22 11:42:56.050 alembic.runtime.migration migration:327] Running stamp_revision  -> 3ec6993fe20c
[36mjupyterhub_1     |[0m [D 2018-05-22 11:42:56.052 alembic.runtime.migration migration:516] new branch insert 3ec6993fe20c
[36mjupyterhub_1     |[0m [W 2018-05-22 11:42:56.211 JupyterHub app:955] No admin users, admin interface will be unavailable.
[36mjupyterhub_1     |[0m [W 2018-05-22 11:42:56.212 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
[36mjupyterhub_1     |[0m [I 2018-05-22 11:42:56.212 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
[36mjupyterhub_1     |[0m [I 2018-05-22 11:42:56.487 JupyterHub app:1073] Adding API token for service: notebooks
[36mjupyterhub_1     |[0m [D 2018-05-22 11:42:56.553 JupyterHub app:1241] Loaded users: 
[36mjupyterhub_1     |[0m [I 2018-05-22 11:42:56.569 JupyterHub app:1528] Hub API listening on http://0.0.0.0:8081/hub/
[36mjupyterhub_1     |[0m [W 2018-05-22 11:42:56.573 JupyterHub proxy:415] 
[36mjupyterhub_1     |[0m     Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
[36mjupyterhub_1     |[0m     Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
[36mjupyterhub_1     |[0m     
[36mjupyterhub_1     |[0m [W 2018-05-22 11:42:56.576 JupyterHub proxy:456] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[36mjupyterhub_1     |[0m [I 2018-05-22 11:42:56.579 JupyterHub proxy:458] Starting proxy @ http://*:8000/
[36mjupyterhub_1     |[0m [D 2018-05-22 11:42:56.586 JupyterHub proxy:459] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://jupyterhub:8081/hub/error']
[36mjupyterhub_1     |[0m 11:42:57.142 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
[36mjupyterhub_1     |[0m 11:42:57.148 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[36mjupyterhub_1     |[0m [D 2018-05-22 11:42:57.209 JupyterHub proxy:491] Proxy started and appears to be up
[36mjupyterhub_1     |[0m [I 2018-05-22 11:42:57.217 JupyterHub app:1551] Adding external service notebooks at http://notebooks:8000
[36mjupyterhub_1     |[0m [D 2018-05-22 11:42:57.294 JupyterHub utils:171] Server at http://notebooks:8000/services/notebooks/ responded with 302
[36mjupyterhub_1     |[0m [D 2018-05-22 11:42:57.302 JupyterHub proxy:552] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
[36mjupyterhub_1     |[0m [W 2018-05-22 11:42:57.344 JupyterHub proxy:304] Adding missing default route
[36mjupyterhub_1     |[0m [I 2018-05-22 11:42:57.344 JupyterHub proxy:370] Adding default route for Hub: / => http://jupyterhub:8081
[36mjupyterhub_1     |[0m [D 2018-05-22 11:42:57.350 JupyterHub proxy:552] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/
[36mjupyterhub_1     |[0m 11:42:57.360 - info: [ConfigProxy] 200 GET /api/routes 
[36mjupyterhub_1     |[0m [W 2018-05-22 11:42:57.361 JupyterHub proxy:348] Adding missing route for notebooks (<jupyterhub.objects.Server object at 0x7f7049c66208>)
[36mjupyterhub_1     |[0m [I 2018-05-22 11:42:57.367 JupyterHub proxy:211] Adding service notebooks to proxy /services/notebooks/ => http://notebooks:8000
[36mjupyterhub_1     |[0m [D 2018-05-22 11:42:57.371 JupyterHub proxy:552] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/services/notebooks
[36mjupyterhub_1     |[0m 11:42:57.384 - info: [ConfigProxy] Adding route /services/notebooks -> http://notebooks:8000
[36mjupyterhub_1     |[0m 11:42:57.391 - info: [ConfigProxy] 201 POST /api/routes/services/notebooks 
[36mjupyterhub_1     |[0m 11:42:57.397 - info: [ConfigProxy] Adding route / -> http://jupyterhub:8081
[36mjupyterhub_1     |[0m [I 2018-05-22 11:42:57.400 JupyterHub app:1581] JupyterHub is now running at http://:8000/
[36mjupyterhub_1     |[0m 11:42:57.402 - info: [ConfigProxy] 201 POST /api/routes/ 
[36mjupyterhub_1     |[0m [I 2018-05-22 11:43:10.775 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 1.93ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:43:31.048 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 4.05ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:43:51.240 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.84ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:43:57.404 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 11:44:11.322 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.56ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:44:31.444 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 10.28ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:44:51.612 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 11.75ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:44:57.411 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 11:45:11.788 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.77ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:45:31.903 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.91ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:45:52.049 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.75ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:45:57.417 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 11:46:12.172 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.77ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:46:32.254 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 3.33ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:46:52.346 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.89ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:46:57.405 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 11:47:12.450 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.61ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:47:32.553 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 2.23ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:47:52.638 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 2.11ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:47:57.406 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [D 2018-05-22 11:47:57.407 JupyterHub proxy:552] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
[36mjupyterhub_1     |[0m 11:47:57.411 - info: [ConfigProxy] 200 GET /api/routes 
[36mjupyterhub_1     |[0m [I 2018-05-22 11:48:12.738 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 2.40ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:48:32.819 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 2.14ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:48:52.935 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.91ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:48:57.404 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 11:49:13.040 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 2.23ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:49:33.144 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 1.19ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:49:53.271 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 2.14ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:49:57.404 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 11:50:13.356 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.55ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:50:33.442 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.75ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:50:53.572 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.68ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:50:57.405 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 11:51:13.656 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.60ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:51:33.751 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.59ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:51:53.837 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.57ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:51:57.404 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 11:52:13.919 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 1.12ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:52:34.017 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 1.47ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:52:54.128 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 1.47ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:52:57.405 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [D 2018-05-22 11:52:57.407 JupyterHub proxy:552] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
[36mjupyterhub_1     |[0m 11:52:57.413 - info: [ConfigProxy] 200 GET /api/routes 
[36mjupyterhub_1     |[0m [I 2018-05-22 11:53:14.252 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 1.55ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:53:34.341 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.60ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:53:54.475 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.68ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:53:57.406 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 11:54:14.551 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 1.62ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:54:34.648 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.60ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:54:54.723 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.55ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:54:57.406 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 11:55:14.808 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.86ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:55:34.887 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.87ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:55:54.970 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.54ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:55:57.405 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 11:56:15.064 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.58ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:56:35.158 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 1.49ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:56:55.253 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.88ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:56:57.405 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 11:57:15.353 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.65ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:57:35.442 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.62ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:57:55.527 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.72ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:57:57.404 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [D 2018-05-22 11:57:57.405 JupyterHub proxy:552] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
[36mjupyterhub_1     |[0m 11:57:57.407 - info: [ConfigProxy] 200 GET /api/routes 
[36mjupyterhub_1     |[0m [I 2018-05-22 11:58:15.621 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 2.76ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:58:35.723 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.53ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:58:55.811 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.68ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:58:57.403 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 11:59:15.925 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.86ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:59:36.054 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.86ms
[36mjupyterhub_1     |[0m [I 2018-05-22 11:59:56.139 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 2.68ms
[36mjupyterhub_1     |[0m [D 2018-05-22 11:59:57.404 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 12:00:16.444 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 1.66ms
[36mjupyterhub_1     |[0m [I 2018-05-22 12:00:36.670 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.76ms
[36mjupyterhub_1     |[0m [I 2018-05-22 12:00:56.955 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 1.00ms
[36mjupyterhub_1     |[0m [D 2018-05-22 12:00:57.404 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 12:01:17.102 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.64ms
[36mjupyterhub_1     |[0m [I 2018-05-22 12:01:37.196 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 1.88ms
[36mjupyterhub_1     |[0m [I 2018-05-22 12:01:57.277 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 1.41ms
[36mjupyterhub_1     |[0m [D 2018-05-22 12:01:57.405 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [I 2018-05-22 12:02:17.430 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 1.19ms
[36mjupyterhub_1     |[0m [I 2018-05-22 12:02:37.593 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.76ms
[36mjupyterhub_1     |[0m [I 2018-05-22 12:02:53.563 JupyterHub log:122] 302 GET /services/projects/cramakri/weather-zh/83d2a23581eaa829c6457684ef962966a16dc7db/notebooks/Analysis.ipynb??branch=master → /hub/services/projects/cramakri/weather-zh/83d2a23581eaa829c6457684ef962966a16dc7db/notebooks/Analysis.ipynb??branch=master (@172.19.0.1) 4.93ms
[36mjupyterhub_1     |[0m [W 2018-05-22 12:02:53.773 JupyterHub log:122] 404 GET /hub/services/projects/cramakri/weather-zh/83d2a23581eaa829c6457684ef962966a16dc7db/notebooks/Analysis.ipynb??branch=master (@172.19.0.1) 177.52ms
[36mjupyterhub_1     |[0m [D 2018-05-22 12:02:54.045 JupyterHub log:122] 304 GET /favicon.ico (@172.19.0.1) 16.50ms
[36mjupyterhub_1     |[0m [D 2018-05-22 12:02:57.408 JupyterHub app:1182] External service notebooks running at http://notebooks:8000
[36mjupyterhub_1     |[0m [D 2018-05-22 12:02:57.409 JupyterHub proxy:552] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
[36mjupyterhub_1     |[0m 12:02:57.411 - info: [ConfigProxy] 200 GET /api/routes 
[36mjupyterhub_1     |[0m [I 2018-05-22 12:02:57.681 JupyterHub log:122] 200 GET /hub/api (@::ffff:127.0.0.1) 0.60ms

**Comment by rokroskar** [comment]
@erbou the issue was a stale configuration file -- can you please pull the latest changes to this branch and retry?

**Pull request merged**
