### PR TITLE
Changes for UI 1.0.0

### PR DESCRIPTION
**Pull request by ciyer**
Changes that go with the new UI design.

/deploy

### CODE REVIEW

**Review by lorenzo-cavazzi — APPROVED** [review]
Great to see this getting merged!
Acceptance tests and documentation changes have already been reviewed separately.

I would still run the acceptance tests also on this branch before merging.

**Comment by rokroskar** [comment]
why deploy ui@master? It's set to 1.0.0 in the `requirements.yaml`

**Comment by ciyer** [comment]
> why deploy ui@master? It's set to 1.0.0 in the `requirements.yaml`

That was left over from before. The change to `requrements.yaml` was only in the very most recent commit.

**Comment by rokroskar** [comment]
that's what I figured - we still want acceptance tests to run though - I put "/deploy" back

**Review by pameladelgado — APPROVED** [review]
🎉 acceptance tests have passed, we are ready to merge this!

**Pull request merged**
