### PR TITLE
Fix acceptance tests

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
Update to support UI changes SwissDataScienceCenter/renku-ui#1123

### CODE REVIEW

**Comment by rokroskar** [comment]
I guess 38c9ce7 is a leftover from starting from master?

**Comment by lorenzo-cavazzi** [comment]
ah yes. Should I remove it? It will make its way into `development` later anyway

**Comment by rokroskar** [comment]
yes, it will, but I'm not sure if it will cause an unnecessary merge conflict

**Comment by lorenzo-cavazzi** [comment]
I can remove it just to be safe :smile:

**Comment by lorenzo-cavazzi** [comment]
Alright, a good old `--force` should have fixed it.

**Review by rokroskar — APPROVED** [review]

**Pull request merged**
